version: '3.5'

services:
        web:
                build:
                        context: ../../
                        dockerfile: docker/dev/Dockerfile
                        args:
                                app_name: ${APP_NAME}
                                python_image_version: ${PYTHON_IMAGE_VERSION}
                                repo_release_version: ${REPO_RELEASE_VERSION}
                image: ${DOCKER_USERNAME}/flask-sql-ci-web:${APP_VERSION}-dev
                environment:
                        FLASK_APP: autoapp.py
                        FLASK_DEBUG: 1
                        FLASK_ENV: development
                        DATABASE_URL: sqlite:////tmp/dev.db
                        SECRET_KEY: not-so-secret
                ports:
                        - 5000:5000
                        - 2992:2992
                volumes:
                        - type: bind
                          source: ../../${APP_NAME}
                          target: /root/${APP_NAME}
                        - /root/${APP_NAME}/node_modules
