apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: myflaskapp
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    app: myflaskapp
    tier: web
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: myflaskapp
    tier: web
spec:
  selector:
    matchLabels:
      app: myflaskapp
      tier: web
  replicas: 2
  strategy:
    type: Recreate 
  template:
    metadata:
      labels:
        app: myflaskapp
        tier: web
    spec:
      containers:
      - image: takacsmark/flask-sql-ci-web:2.0.0-prod
        name: web
        env:
        - name: POSTGRES_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: db-password
              key: _db_password.txt
        - name: APP_SECRET
          valueFrom: 
            secretKeyRef:
              name: app-secret
              key: _app_secret.txt
        ports:
        - containerPort: 5000
          name: web
      restartPolicy: Always
